### PR TITLE
add zip utility

### PR DESCRIPTION
**Pull request by vincentcr**
useful for building AWS lambda packages.

### CODE REVIEW

**Comment by FelicianoTech** [comment]
Hi @vincentcr, I agree this would be useful.

Can you please fix this PR though so that the packages stay in alphabetical order?

So instead of this:

```
	gzip \
	jq \
	openssh \
	zip \
	tar \
	wget
```

it'll be this:

```
	gzip \
	jq \
	openssh \
	tar \
	wget \
	zip
```

**Comment by vincentcr** [comment]
@felicianotech done!

**Comment by FelicianoTech** [comment]
Thank you. 😊

**Comment by vincentcr** [comment]
Thanks Ricardo! Could you kindly rebuild the aws image based on this change
as well, so I can use it?

>

**Comment by FelicianoTech** [comment]
@vincentcr The AWS image [has been updated](https://github.com/cibuilds/aws/pull/97) for the AWS CLI v1.16.10 release. Starting from that version, the images include the `zip` command.

I hope that helps.

**Comment by vincentcr** [comment]
Perfect! Thanks @felicianotech .

**Pull request merged**
